spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: alan
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: none   #create | create-drop | update